In [4]:
# Import libraries

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [9]:
# Load the data

data = pd.read_csv("Loan_Repayment_Training_Data.csv")

data.head(10)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Employment Status,Existing Loans,Marital Status,Education Level,Repayment
0,25,13.40,1.00,501,236,Self-Employed,3,Single,Graduate,0
1,56,5.57,12.30,545,115,Salaried,3,Single,Graduate,0
2,50,8.73,22.09,803,72,Self-Employed,1,Single,Post-Graduate,1
3,41,18.80,1.00,761,129,Self-Employed,2,Married,Graduate,1
4,41,8.86,16.05,615,192,Salaried,4,Married,Graduate,0
5,59,15.43,7.70,545,83,Self-Employed,2,Single,High School,0
6,25,5.40,9.57,450,22,Self-Employed,0,Single,High School,0
7,52,9.77,2.63,631,23,Self-Employed,3,Married,High School,0
8,30,5.30,7.66,870,206,Self-Employed,2,Married,Graduate,1
9,26,8.97,19.10,719,37,Unemployed,2,Married,Graduate,0

In [14]:
# Define X and y

X = data.drop("Repayment ",axis=1)
y = data["Repayment "]

In [15]:
text_columns = ["Employment Status","Marital Status","Education Level"]

X = pd.get_dummies(X,columns=text_columns)

X.head(20)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Existing Loans,Employment Status_Salaried,Employment Status_Self-Employed,Employment Status_Unemployed,Marital Status_Married,Marital Status_Single,Education Level_Graduate,Education Level_High School,Education Level_Post-Graduate
0,25,13.40,1.00,501,236,3,False,True,False,False,True,True,False,False
1,56,5.57,12.30,545,115,3,True,False,False,False,True,True,False,False
2,50,8.73,22.09,803,72,1,False,True,False,False,True,False,False,True
3,41,18.80,1.00,761,129,2,False,True,False,True,False,True,False,False
4,41,8.86,16.05,615,192,4,True,False,False,True,False,True,False,False
5,59,15.43,7.70,545,83,2,False,True,False,False,True,False,True,False
6,25,5.40,9.57,450,22,0,False,True,False,False,True,False,True,False
7,52,9.77,2.63,631,23,3,False,True,False,True,False,False,True,False
8,30,5.30,7.66,870,206,2,False,True,False,True,False,True,False,False
9,26,8.97,19.10,719,37,2,False,False,True,True,False,True,False,False
10,45,16.04,14.08,630,156,3,True,False,False,True,False,False,True,False
11,64,1.00,22.13,722,99,4,True,False,False,False,True,True,False,False
12,54,13.61,18.24,540,189,1,True,False,False,True,False,True,False,False
13,55,12.43,13.07,653,25,2,False,True,False,False,True,False,False,True
14,53,7.44,22.21,689,216,0,True,False,False,False,True,True,False,False
15,56,2.32,13.07,672,171,3,True,False,False,False,True,True,False,False
16,44,11.43,15.80,751,114,2,True,False,False,True,False,False,True,False
17,27,7.82,7.92,711,59,1,False,True,False,True,False,False,False,True
18,58,12.40,10.47,740,234,3,True,False,False,False,True,True,False,False
19,41,11.13,5.12,618,80,2,False,True,False,False,True,True,False,False

In [16]:
# Splitting the data in training and test data

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
# Training the Logistic Regression model

bhupesh_ml = LogisticRegression()

bhupesh_ml.fit(X_train,y_train)

print("Model trained successfully")

Model trained successfully

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [18]:
predicted_result = bhupesh_ml.predict(X_test)

In [20]:
# Evaluation of the model

accuracy = accuracy_score(y_test, predicted_result)

print("The accuracy of the model is:", accuracy*100,"%")

The accuracy of the model is: 60.0 %

In [21]:
# Load the new data 

new_data = pd.read_csv("Loan_Repayment_Test_Data_NoLabel.csv")

new_data.head(20)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Employment Status,Existing Loans,Marital Status,Education Level
0,35,5.56,7.84,647,221,Salaried,2,Married,Graduate
1,47,16.97,14.23,856,39,Self-Employed,2,Single,Graduate
2,25,8.77,5.36,596,30,Salaried,1,Married,Post-Graduate
3,22,9.64,10.40,618,128,Salaried,2,Single,Post-Graduate
4,58,13.50,14.40,765,239,Salaried,0,Married,Graduate
5,51,27.69,34.41,731,120,Salaried,2,Married,Graduate
6,62,18.68,26.27,713,205,Salaried,1,Married,Graduate
7,60,6.63,3.84,727,231,Salaried,2,Married,Post-Graduate
8,50,1.97,1.00,642,50,Salaried,1,Married,Post-Graduate
9,65,14.59,19.96,593,26,Self-Employed,4,Married,Graduate
10,59,7.31,2.61,856,118,Salaried,1,Married,Graduate
11,39,10.16,6.05,586,49,Salaried,2,Married,Graduate
12,24,10.53,7.27,501,137,Self-Employed,0,Single,Graduate
13,47,11.11,14.48,627,191,Salaried,1,Married,Graduate
14,29,10.28,9.44,780,220,Salaried,1,Single,Post-Graduate
15,49,8.17,7.66,498,240,Self-Employed,0,Single,Graduate
16,27,1.00,1.18,615,225,Unemployed,1,Married,Graduate
17,62,13.49,20.20,790,90,Unemployed,0,Single,Post-Graduate
18,25,16.95,24.58,573,52,Self-Employed,0,Single,Post-Graduate
19,51,4.46,1.26,718,87,Unemployed,0,Married,Graduate

In [23]:
text_columns = ["Employment Status","Marital Status","Education Level"]

X_dummies = pd.get_dummies(new_data,columns=text_columns)

X_dummies.head(20)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Existing Loans,Employment Status_Salaried,Employment Status_Self-Employed,Employment Status_Unemployed,Marital Status_Married,Marital Status_Single,Education Level_Graduate,Education Level_High School,Education Level_Post-Graduate
0,35,5.56,7.84,647,221,2,True,False,False,True,False,True,False,False
1,47,16.97,14.23,856,39,2,False,True,False,False,True,True,False,False
2,25,8.77,5.36,596,30,1,True,False,False,True,False,False,False,True
3,22,9.64,10.40,618,128,2,True,False,False,False,True,False,False,True
4,58,13.50,14.40,765,239,0,True,False,False,True,False,True,False,False
5,51,27.69,34.41,731,120,2,True,False,False,True,False,True,False,False
6,62,18.68,26.27,713,205,1,True,False,False,True,False,True,False,False
7,60,6.63,3.84,727,231,2,True,False,False,True,False,False,False,True
8,50,1.97,1.00,642,50,1,True,False,False,True,False,False,False,True
9,65,14.59,19.96,593,26,4,False,True,False,True,False,True,False,False
10,59,7.31,2.61,856,118,1,True,False,False,True,False,True,False,False
11,39,10.16,6.05,586,49,2,True,False,False,True,False,True,False,False
12,24,10.53,7.27,501,137,0,False,True,False,False,True,True,False,False
13,47,11.11,14.48,627,191,1,True,False,False,True,False,True,False,False
14,29,10.28,9.44,780,220,1,True,False,False,False,True,False,False,True
15,49,8.17,7.66,498,240,0,False,True,False,False,True,True,False,False
16,27,1.00,1.18,615,225,1,False,False,True,True,False,True,False,False
17,62,13.49,20.20,790,90,0,False,False,True,False,True,False,False,True
18,25,16.95,24.58,573,52,0,False,True,False,False,True,False,False,True
19,51,4.46,1.26,718,87,0,False,False,True,True,False,True,False,False

In [24]:
new_data["Predicted Result"] = bhupesh_ml.predict(X_dummies)

new_data.head(10)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Employment Status,Existing Loans,Marital Status,Education Level,Predicted Result
0,35,5.56,7.84,647,221,Salaried,2,Married,Graduate,0
1,47,16.97,14.23,856,39,Self-Employed,2,Single,Graduate,1
2,25,8.77,5.36,596,30,Salaried,1,Married,Post-Graduate,1
3,22,9.64,10.40,618,128,Salaried,2,Single,Post-Graduate,1
4,58,13.50,14.40,765,239,Salaried,0,Married,Graduate,0
5,51,27.69,34.41,731,120,Salaried,2,Married,Graduate,0
6,62,18.68,26.27,713,205,Salaried,1,Married,Graduate,0
7,60,6.63,3.84,727,231,Salaried,2,Married,Post-Graduate,1
8,50,1.97,1.00,642,50,Salaried,1,Married,Post-Graduate,1
9,65,14.59,19.96,593,26,Self-Employed,4,Married,Graduate,0

In [25]:
new_data["Predicted Result"] = new_data["Predicted Result"].replace(1,"Repay")
new_data["Predicted Result"] = new_data["Predicted Result"].replace(0,"Default")

In [26]:
new_data.head(10)

,Age,Annual Income (LPA),Borrowed Amount (LPA),Credit Score,Loan Tenure (months),Employment Status,Existing Loans,Marital Status,Education Level,Predicted Result
0,35,5.56,7.84,647,221,Salaried,2,Married,Graduate,Default
1,47,16.97,14.23,856,39,Self-Employed,2,Single,Graduate,Repay
2,25,8.77,5.36,596,30,Salaried,1,Married,Post-Graduate,Repay
3,22,9.64,10.40,618,128,Salaried,2,Single,Post-Graduate,Repay
4,58,13.50,14.40,765,239,Salaried,0,Married,Graduate,Default
5,51,27.69,34.41,731,120,Salaried,2,Married,Graduate,Default
6,62,18.68,26.27,713,205,Salaried,1,Married,Graduate,Default
7,60,6.63,3.84,727,231,Salaried,2,Married,Post-Graduate,Repay
8,50,1.97,1.00,642,50,Salaried,1,Married,Post-Graduate,Repay
9,65,14.59,19.96,593,26,Self-Employed,4,Married,Graduate,Default

In [28]:
new_data.to_excel("Tharun.xlsx", index=False)